import { Header } from "@/components/layouts/Header";
import "./globals.css";
import Footer from "@/components/layouts/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="grow overflow-hidden">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
